# coding: utf-8

keymap = {
    "KC_GRAVE": "¨\n¸",
    "KC_1": "!\n1 ~",
    "KC_2": '"\n2 ˇ',
    "KC_3": "#\n3 ^",
    "KC_4": "$\n4 ˘",
    "KC_5": "%\n5 °",
    "KC_6": "&\n6 ˛",
    "KC_7": "/\n7 `",
    "KC_8": "(\n8 ˙",
    "KC_9": ")\n9 ´",
    "KC_0": "=\n0 ˝",
    "KC_Q": "Q\n   \\",
    "KC_W": "W\n   |",
    "KC_E": "E\n   €",
    "KC_Y": "Z",
    "KC_MINUS": "?\n' ¨",
    "KC_EQUAL": "*\n+ ¸",
    "KC_LBRACKET": "Š\n   ÷",
    "KC_RBRACKET": "Đ\n   ×",
    "KC_BSLASH": "Ž\n   ¤",
    "KC_F": "F\n   [",
    "KC_G": "G\n   ]",
    "KC_K": "K\n   ł",
    "KC_L": "L\n   Ł",
    "KC_SCOLON": "Č",
    "KC_QUOTE": "Ć\n   ß",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_Z": "Y",
    "KC_V": "V\n   @",
    "KC_B": "B\n   {",
    "KC_N": "N\n   }",
    "KC_M": "M\n   §",
    "KC_COMMA": ";\n,",
    "KC_DOT": ":\n.",
    "KC_SLASH": "_\n-",
    "KC_TILD": "¨",
    "KC_AT": '"',
    "KC_CIRC": "&",
    "KC_AMPR": "/",
    "KC_ASTR": "(",
    "KC_LPRN": ")",
    "KC_RPRN": "=",
    "KC_UNDS": "?",
    "KC_PLUS": "*",
    "KC_LCBR": "Š",
    "KC_RCBR": "Đ",
    "KC_LT": ";",
    "KC_GT": ":",
    "KC_COLN": "Č",
    "KC_QUES": "_",
    "KC_DQUO": "Ć",
    "KC_PIPE": "Ž",
    "KC_NONUS_HASH": "Ž\n   ¤",
    "KC_KP_DOT": ","
}