# coding: utf-8

keymap = {
    "KC_GRAVE": "§\n½",
    "KC_2": '"\n2   @',
    "KC_3": "#\n3   £",
    "KC_4": "¤\n4   $",
    "KC_6": "&\n6",
    "KC_7": "/\n7   {",
    "KC_8": "(\n8   [",
    "KC_9": ")\n9   ]",
    "KC_0": "=\n0   }",
    "KC_MINUS": "?\n+",
    "KC_EQUAL": "`\n´   |",
    "KC_LBRACKET": "Å",
    "KC_RBRACKET": "^\n¨   ~",
    "KC_SCOLON": "Æ",
    "KC_QUOTE": "Ø",
    "KC_NONUS_HASH": "*\n'",
    "KC_NONUS_BSLASH": ">\n<   \\",
    "KC_BSLASH": "*\n'",
    "KC_COMMA": ";\n,",
    "KC_DOT": ":\n.",
    "KC_SLASH": "_\n-",
    "KC_TILD": "§",
    "KC_AT": "\"",
    "KC_DLR": "¤",
    "KC_CIRC": "&",
    "KC_AMPR": "/",
    "KC_ASTR": "(",
    "KC_LPRN": ")",
    "KC_RPRN": "=",
    "KC_UNDS": "?",
    "KC_PLUS": "`",
    "KC_LCBR": "Å",
    "KC_RCBR": "^",
    "KC_LT": ";",
    "KC_GT": ":",
    "KC_COLN": "Æ",
    "KC_PIPE": "*",
    "KC_QUES": "_",
    "KC_DQUO": "Ø",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)"
}
