# coding: utf-8

keymap = {
    "KC_GRAVE": "~ ~\n` `",
    "KC_1": "! ¹\n1 ¡",
    "KC_2": "@ ²\n2 ª",
    "KC_3": "# ³\n3 º",
    "KC_4": "$ ¥\n4 £",
    "KC_5": "% ¢\n5 €",
    "KC_6": "^ ˇ\n6 ^",
    "KC_7": "& ¯\n7 ˚",
    "KC_8": "* ‚\n8 „",
    "KC_9": "( ‘\n9 “",
    "KC_0": ") ’\n0 ”",
    "KC_Q": "  Æ\nQ æ",
    "KC_W": "  Å\nW å",
    "KC_E": "  Ë\nE ë",
    "KC_R": "  Ý\nR ý",
    "KC_T": "  Þ\nT þ",
    "KC_Y": "  Ÿ\nY ÿ",
    "KC_U": "  Ü\nU ü",
    "KC_I": "  Ï\nI ï",
    "KC_O": "  Ö\nO ö",
    "KC_P": "  Œ\nP œ",
    "KC_MINUS": "_ №\n- ©",
    "KC_EQUAL": "+ ÷\n= ×",
    "KC_LBRACKET": "{ ‹\n[ «",
    "KC_RBRACKET": "} ›\n] »",
    "KC_BSLASH": "| ¦\n\ ¬",
    "KC_A": "  Ä\nA ä",
    "KC_S": "  §\nS ß",
    "KC_D": "  Đ\nD đ",
    "KC_F": "  È\nF è",
    "KC_G": "  É\nG é",
    "KC_H": "  Ù\nH ù",
    "KC_J": "  Ú\nJ ú",
    "KC_K": "  Ĳ\nK ĳ",
    "KC_L": "  Ø\nL ø",
    "KC_SCOLON": ": ·\n; °",
    "KC_QUOTE": "\" ¨\n' ´",
    "KC_NONUS_BSLASH": "|\n\\",
    "KC_Z": "  À\nZ à",
    "KC_X": "  Á\nX á",
    "KC_C": "  Ç\nC ç",
    "KC_V": "  Ì\nV ì",
    "KC_B": "  Í\nB í",
    "KC_N": "  Ñ\nN ñ",
    "KC_M": "  √\nM Ω",
    "KC_COMMA": "< Ò\n, ò",
    "KC_DOT": "> Ó\n. ó",
    "KC_SLASH": "? …\n/ ¿",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)",
    "KC_TILD":  "~ ~",
    "KC_EXLM":  "! ¹",
    "KC_AT":    "@ ²",
    "KC_HASH":  "# ³",
    "KC_DLR":   "$ ¥",
    "KC_PERC":  "% ¢",
    "KC_CIRC":  "^ ˇ",
    "KC_AMPR":  "& ¯",
    "KC_ASTR":  "* ‚",
    "KC_LPRN":  "( ‘",
    "KC_RPRN":  ") ’",
    "KC_UNDS":  "_ №",
    "KC_PLUS":  "+ ÷",
    "KC_LCBR": "{ ‹",
    "KC_RCBR": "} ›",
    "KC_LT": "< Ò",
    "KC_GT": "> Ó",
    "KC_COLN": ": ·",
    "KC_QUES": "? …",
    "KC_DQUO": '" ¨'
}