# coding: utf-8

keymap = {
    "KC_GRAVE": "~ ~\n` `",
    "KC_1": "! ¹\n1 ¡",
    "KC_2": "@ ²\n2 ª",
    "KC_3": "# ³\n3 º",
    "KC_4": "$ ¥\n4 £",
    "KC_5": "% ¢\n5 €",
    "KC_6": "^ ˇ\n6 ^",
    "KC_7": "& ¯\n7 ˚",
    "KC_8": "* ‚\n8 „",
    "KC_9": "( ‘\n9 “",
    "KC_0": ") ’\n0 ”",
    "KC_Q": "Q\n   æ",
    "KC_W": "W\n   å",
    "KC_E": "E\n   ë",
    "KC_R": "R\n   ý",
    "KC_T": "T\n   þ",
    "KC_Y": "Y\n   ÿ",
    "KC_U": "U\n   ü",
    "KC_I": "I\n   ï",
    "KC_O": "O\n   ö",
    "KC_P": "P\n   œ",
    "KC_MINUS": "_ №\n- ©",
    "KC_EQUAL": "+ ÷\n= ×",
    "KC_LBRACKET": "{ ‹\n[ «",
    "KC_RBRACKET": "} ›\n] »",
    "KC_BSLASH": "| ¦\n\\ ¬",
    "KC_A": "A\n   ä",
    "KC_S": "S\n   ß",
    "KC_D": "D\n   đ",
    "KC_F": "F\n   è",
    "KC_G": "G\n   é",
    "KC_H": "H\n   ù",
    "KC_J": "J\n   ú",
    "KC_K": "K\n   ĳ",
    "KC_L": "L\n   ø",
    "KC_SCOLON": ": ·\n; °",
    "KC_QUOTE": "\" ¨\n' ´",
    "KC_NONUS_BSLASH": "|\n\\",
    "KC_Z": "Z\n   à",
    "KC_X": "X\n   á",
    "KC_C": "C\n   ç",
    "KC_V": "V\n   ì",
    "KC_B": "B\n   í",
    "KC_N": "N\n   ñ",
    "KC_M": "  √\nM Ω",
    "KC_COMMA": "< Ò\n, ò",
    "KC_DOT": "> Ó\n. ó",
    "KC_SLASH": "? …\n/ ¿",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)",
    "KC_TILD":  "~ ~",
    "KC_EXLM":  "! ¹",
    "KC_AT":    "@ ²",
    "KC_HASH":  "# ³",
    "KC_DLR":   "$ ¥",
    "KC_PERC":  "% ¢",
    "KC_CIRC":  "^ ˇ",
    "KC_AMPR":  "& ¯",
    "KC_ASTR":  "* ‚",
    "KC_LPRN":  "( ‘",
    "KC_RPRN":  ") ’",
    "KC_UNDS":  "_ №",
    "KC_PLUS":  "+ ÷",
    "KC_LCBR": "{ ‹",
    "KC_RCBR": "} ›",
    "KC_LT": "< Ò",
    "KC_GT": "> Ó",
    "KC_COLN": ": ·",
    "KC_QUES": "? …",
    "KC_DQUO": '" ¨'
}