# coding: utf-8

keymap = {
    "KC_GRAVE": "²",
    "KC_1": "1\n&",
    "KC_2": "2\né",
    "KC_3": '3\n"',
    "KC_4": "4\n'",
    "KC_5": "5\n(",
    "KC_6": "6\n-",
    "KC_7": "7\nè",
    "KC_8": "8\n_",
    "KC_9": "9\nç",
    "KC_0": "0\nà",
    "KC_MINUS": "°\n)",
    "KC_Q": "A",
    "KC_W": "Z",
    "KC_LBRACKET": "¨\n^",
    "KC_RBRACKET": "£\n$",
    "KC_A": "Q",
    "KC_SCOLON": "M",
    "KC_QUOTE": "%\nù",
    "KC_NONUS_HASH": "µ\n*",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_Z": "W",
    "KC_M": "?\n,",
    "KC_COMMA": ".\n;",
    "KC_DOT": "/\n:",
    "KC_SLASH": "§\n!",
}

keymap_mac = {
    "KC_GRAVE": "#\n@",
    "KC_1": "1\n&",
    "KC_2": "2\né",
    "KC_3": '3\n"',
    "KC_4": "4\n'",
    "KC_5": "5\n(",
    "KC_6": "6\n§",
    "KC_7": "7\nè",
    "KC_8": "8\n!",
    "KC_9": "9\nç",
    "KC_0": "0\nà",
    "KC_MINUS": "°\n)",
    "KC_EQUAL": "_\n-",
    "KC_Q": "A",
    "KC_W": "Z",
    "KC_LBRACKET": "¨\n^",
    "KC_RBRACKET": "*\n$    €",
    "KC_A": "Q",
    "KC_SCOLON": "M",
    "KC_QUOTE": "%\nù",
    "KC_NONUS_HASH": "£\n`",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_Z": "W",
    "KC_M": "?\n,",
    "KC_COMMA": ".\n;",
    "KC_DOT": "/\n:",
    "KC_SLASH": "+\n=",
}

keymap_bepo = {
    "KC_GRAVE": "$\n# –",
    "KC_1": "\"\n1 —",
    "KC_2": "«\n2 <",
    "KC_3": "»\n3 >",
    "KC_4": "(\n4 [",
    "KC_5": ")\n5 ]",
    "KC_6": "@\n6 ^",
    "KC_7": "+\n7 ±",
    "KC_8": "-\n8 −",
    "KC_9": "/\n9 ÷",
    "KC_0": "*\n0 ×",
    "KC_MINUS": "=\n° ≠",
    "KC_EQUAL": "%\n`",
    "KC_Q": "B\n     |",
    "KC_W": "É",
    "KC_E": "P\n     &",
    "KC_R": "O\n     œ",
    "KC_T": "È",
    "KC_Y": "^\n!",
    "KC_U": "V",
    "KC_I": "D",
    "KC_O": "L",
    "KC_P": "J",
    "KC_LBRACKET": "Z",
    "KC_RBRACKET": "W",
    "KC_A": "A\n     æ",
    "KC_S": "U\n     ù",
    "KC_D": "I\n     ¨",
    "KC_F": "E\n     €",
    "KC_G": ",\n;",
    "KC_H": "C\n",
    "KC_J": "T\n",
    "KC_K": "S",
    "KC_L": "R",
    "KC_SCOLON": "N",
    "KC_QUOTE": "M",
    "KC_NONUS_HASH": "Ç",
    "KC_NONUS_BSLASH": "Ê\n /",
    "KC_Z": "À\n     \\",
    "KC_X": "Y\n     {",
    "KC_C": "X\n     }",
    "KC_V": ".\n: …",
    "KC_B": "K    ~",
    "KC_N": "'\n ?",
    "KC_M": "Q",
    "KC_COMMA": "G",
    "KC_DOT": "H",
    "KC_SLASH": "F",
}
