# coding: utf-8

keymap = {
    "KC_GRAVE": "²",
    "KC_1": "1\n&",
    "KC_2": "2\né",
    "KC_3": '3\n"',
    "KC_4": "4\n'",
    "KC_5": "5\n(",
    "KC_6": "6\n-",
    "KC_7": "7\nè",
    "KC_8": "8\n_",
    "KC_9": "9\nç",
    "KC_0": "0\nà",
    "KC_MINUS": "°\n)",
    "KC_Q": "A",
    "KC_W": "Z",
    "KC_LBRACKET": "¨\n^",
    "KC_RBRACKET": "£\n$",
    "KC_A": "Q",
    "KC_SCOLON": "M",
    "KC_QUOTE": "%\nù",
    "KC_NONUS_HASH": "µ\n*",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_Z": "W",
    "KC_M": "?\n,",
    "KC_COMMA": ".\n;",
    "KC_DOT": "/\n:",
    "KC_SLASH": "§\n!",
}
