# coding: utf-8

keymap = {
    "KC_GRAVE": "°\n^",
    "KC_2": '"\n2',
    "KC_3": "§\n3",
    "KC_6": "&\n6",
    "KC_7": "/\n7",
    "KC_8": "(\n8",
    "KC_9": ")\n9",
    "KC_0": "=\n0",
    "KC_MINUS": "?\nß",
    "KC_EQUAL": "`\n´",
    "KC_Y": "Z",
    "KC_LBRACKET": "Ü",
    "KC_RBRACKET": "*\n+",
    "KC_SCOLON": "Ö",
    "KC_QUOTE": "Ä",
    "KC_NONUS_HASH": "'\n#",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_Z": "Y",
    "KC_COMMA": ";\n,",
    "KC_DOT": ":\n.",
    "KC_SLASH": "_\n-",
}
