# coding: utf-8

keymap = {
    "KC_GRAVE": "~\n;    ׳",
    "KC_3": "#\n3    €",
    "KC_4": "#\n4    ₪",
    "KC_5": "%\n5    °",
    "KC_6": "^\n6    ◌֫",
    "KC_7": "&\n7    ◌ֽ",
    "KC_8": "*\n8    ×",
    "KC_9": ")\n9    ᴸᴿᴹ",
    "KC_0": "(\n0    ᴿᴸᴹ",
    "KC_MINUS": "_\n-    ־",
    "KC_EQUAL": "+\n=    –",
    "KC_Q": "Q\n/    ◌ׂ",
    "KC_W": "W\n'    ◌ׁ",
    "KC_E": "E\nק    ◌ָ",
    "KC_R": "R\nר    ◌ֳ",
    "KC_T": "T\nא ",
    "KC_Y": "Y\nט    װ",
    "KC_U": "U    ◌ֺ\nו   ◌ֹ",
    "KC_I": "I\nן",
    "KC_O": "O\nם",
    "KC_P": "P\nפ    ◌ַ",
    "KC_A": "A\nש",
    "KC_S": "S\nד",
    "KC_D": "D\nג",
    "KC_F": "F\nכ",
    "KC_G": "G\nע",
    "KC_H": "H\nי",
    "KC_J": "J\nח",
    "KC_K": "K\nל",
    "KC_L": "L    “\nך",
    "KC_SCOLON": ":    ”\nף",
    "KC_QUOTE": "\"\n,",
    "KC_Z": "Z\nז",
    "KC_X": "X\nס    ◌ֶ",
    "KC_C": "C\nב    ◌ֱ",
    "KC_V": "V\nה",
    "KC_B": "B    ׆\nנ",
    "KC_N": "N\nמ",
    "KC_M": "M\nצ    ◌ֵ",
    "KC_COMMA": "<    ‘\nת    ’",
    "KC_DOT": ">    ’\nץ    ‚",
    "KC_SLASH": "?\n.    ÷",
}