# coding: utf-8

keymap = {
    "KC_GRAVE": "§\n0",
    "KC_1": "'\n1 ~",
    "KC_2": '"\n2 ˇ',
    "KC_3": "+\n3 ^",
    "KC_4": "!\n4 ˘",
    "KC_5": "%\n5 °",
    "KC_6": "/\n6 ˛",
    "KC_7": "=\n7 `",
    "KC_8": "(\n8 ˙",
    "KC_9": ")\n9 ´",
    "KC_0": "Ö\n  ˝",
    "KC_MINUS": "Ü\n  ¨",
    "KC_EQUAL": "Ó\n  ¸",
    "KC_Q": "Q\n  \\",
    "KC_W": "W\n  |",
    "KC_E": "E\n  Ä",
    "KC_Y": "Z",
    "KC_U": "U\n  €",
    "KC_I": "I\n  Í",
    "KC_LBRACKET": "Ő\n  ÷",
    "KC_RBRACKET": "Ú\n  ×",
    "KC_A": "A\n  ä",
    "KC_S": "S\n  đ",
    "KC_D": "D\n  Đ",
    "KC_F": "F\n  [",
    "KC_G": "G\n  ]",
    "KC_J": "J\n  í",
    "KC_K": "K\n  ł",
    "KC_L": "L\n  Ł",
    "KC_SCOLON": "É\n  $",
    "KC_QUOTE": "Á\n  ß",
    "KC_NONUS_HASH": "Ű\n  ¤",
    "KC_NONUS_BSLASH": "Í\n  <",
    "KC_Z": "Y\n  >",
    "KC_X": "X\n  #",
    "KC_C": "C\n  &",
    "KC_V": "V\n  @",
    "KC_B": "B\n  {",
    "KC_N": "N\n  }",
    "KC_COMMA": "?\n, ;",
    "KC_DOT": ":\n.",
    "KC_SLASH": "_\n- *"
}
