# coding: utf-8

keymap = {
    "KC_GRAVE": "|\n\\",
    "KC_1": "!\n1",
    "KC_2": '"\n2',
    "KC_3": "£\n3",
    "KC_6": "&\n6",
    "KC_7": "/\n7",
    "KC_8": "(\n8",
    "KC_9": ")\n9",
    "KC_0": "=\n0",
    "KC_MINUS": "´\n?",
    "KC_EQUAL": "^\nì",
    "KC_E": "E\n   €",
    "KC_LBRACKET": "é\nè  [",
    "KC_RBRACKET": "*\n+  ]",
    "KC_BSLASH": "§\nù",
    "KC_SCOLON": "ç\nò  @",
    "KC_QUOTE": "º\nà  #",
    "KC_NONUS_HASH": "§\nù",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_COMMA": ";\n,",
    "KC_DOT": ":\n.",
    "KC_SLASH": "_\n-",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)",
    "KC_TILD":  "|",
    "KC_AT":    '"',
    "KC_HASH":  "£",
    "KC_CIRC":  "&",
    "KC_AMPR":  "/",
    "KC_ASTR":  "(",
    "KC_LPRN":  ")",
    "KC_RPRN":  "=",
    "KC_UNDS":  "?",
    "KC_PLUS":  "^",
    "KC_LCBR": "é",
    "KC_RCBR": "*",
    "KC_LT": ";",
    "KC_GT": ":",
    "KC_COLN": "ç",
    "KC_PIPE": "§",
    "KC_QUES": "_",
    "KC_DQUO": "°"
}