# coding: utf-8

keymap = {
    "KC_GRAVE": "~ \n` ",
    "KC_1": "! \n1 ",
    "KC_2": "@ \n2 ",
    "KC_3": "# \n3 ",
    "KC_4": "$ \n4 ",
    "KC_5": "% \n5 ",
    "KC_6": "^ \n6 ",
    "KC_7": "& \n7 ",
    "KC_8": "* \n8 ",
    "KC_9": "( \n9 ",
    "KC_0": ") \n0 ",
    "KC_E": "E\n   ę",
    "KC_O": "O\n   ó",
    "KC_MINUS": "_ \n- ",
    "KC_EQUAL": "+ \n= ",
    "KC_LBRACKET": "{ \n[ ",
    "KC_RBRACKET": "} \n] ",
    "KC_BSLASH": "| \n\ ",
    "KC_A": "A\n   ą",
    "KC_S": "S\n   ś",
    "KC_L": "L\n   ł",
    "KC_SCOLON": ": \n; ",
    "KC_QUOTE": "\" \n' ",
    "KC_NONUS_BSLASH": "|\n\\",
    "KC_Z": "Z\n   ż",
    "KC_X": "X\n   ź",
    "KC_C": "C\n   ć",
    "KC_N": "N\n   ń",
    "KC_COMMA": "< \n, ",
    "KC_DOT": "> \n. ",
    "KC_SLASH": "? \n/ ",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)",
}