# coding: utf-8

keymap = {
    "KC_GRAVE": "Ё",
    "KC_2": '"\n2',
    "KC_3": "№\n3",
    "KC_4": ";\n4",
    "KC_6": ":\n6",
    "KC_7": "?\n7",
    "KC_Q": "Q\nЙ",
    "KC_W": "W\nЦ",
    "KC_E": "E\nУ",
    "KC_R": "R\nК",
    "KC_T": "T\nЕ",
    "KC_Y": "Y\nН",
    "KC_U": "U\nГ",
    "KC_I": "I\nШ",
    "KC_O": "O\nЩ",
    "KC_P": "P\nЗ",
    "KC_LBRACKET": "{\n[ Х",
    "KC_RBRACKET": "}\n] Ъ",
    "KC_BSLASH": "| /\n\\",
    "KC_A": "A\nФ",
    "KC_S": "S\nЫ",
    "KC_D": "D\nВ",
    "KC_F": "F\nА",
    "KC_G": "G\nП",
    "KC_H": "H\nР",
    "KC_J": "J\nО",
    "KC_K": "K\nЛ",
    "KC_L": "L\nД",
    "KC_SCOLON": ":\n; Ж",
    "KC_QUOTE": "\"\n' Э",
    "KC_Z": "Z\nЯ",
    "KC_X": "X\nЧ",
    "KC_C": "C\nС",
    "KC_V": "V\nМ",
    "KC_B": "B\nИ",
    "KC_N": "N\nТ",
    "KC_M": "M\nЬ",
    "KC_COMMA": "<\n, Б",
    "KC_DOT": ">\n. Ю",
    "KC_SLASH": "? ,\n/ ."
}
