# coding: utf-8

keymap = {
    "KC_GRAVE": "~\n` Ё",
    "KC_2": '@ "\n2',
    "KC_3": "# №\n3",
    "KC_4": "$ ;\n4",
    "KC_6": "^ :\n6",
    "KC_7": "& ?\n7",
    "KC_Q": "Q\nЙ",
    "KC_W": "W\nЦ",
    "KC_E": "E\nУ",
    "KC_R": "R\nК",
    "KC_T": "T\nЕ",
    "KC_Y": "Y\nН",
    "KC_U": "U\nГ",
    "KC_I": "I\nШ",
    "KC_O": "O\nЩ",
    "KC_P": "P\nЗ",
    "KC_LBRACKET": "{\n[ Х",
    "KC_RBRACKET": "}\n] Ъ",
    "KC_BSLASH": "| /\n\\",
    "KC_A": "A\nФ",
    "KC_S": "S\nЫ",
    "KC_D": "D\nВ",
    "KC_F": "F\nА",
    "KC_G": "G\nП",
    "KC_H": "H\nР",
    "KC_J": "J\nО",
    "KC_K": "K\nЛ",
    "KC_L": "L\nД",
    "KC_SCOLON": ":\n; Ж",
    "KC_QUOTE": "\"\n' Э",
    "KC_Z": "Z\nЯ",
    "KC_X": "X\nЧ",
    "KC_C": "C\nС",
    "KC_V": "V\nМ",
    "KC_B": "B\nИ",
    "KC_N": "N\nТ",
    "KC_M": "M\nЬ",
    "KC_COMMA": "<\n, Б",
    "KC_DOT": ">\n. Ю",
    "KC_SLASH": "? ,\n/ ."
}

universal_braindefender_ortho = {
    
    "KC_GRAVE": "' \"\n(` •)",
    "KC_1": '! 1',
    "KC_2": '@ 2',
    "KC_3": "# 3",
    "KC_4": "$ 4",
    "KC_5": "% 5",
    "KC_6": "^ 6",
    "KC_7": "? 7",
    "KC_8": "* 8",
    "KC_9": "( 9",
    "KC_0": ") 0",
    "KC_MINUS": "- _\n(–)",
    "KC_EQUAL": "= +\n(≠ ±)",

    "KC_Q": "Q\nЙ",
    "KC_W": "W\nЦ",
    "KC_E": "E\nУ",
    "KC_R": "R\nК",
    "KC_T": "T\nЕ (Ë)",
    "KC_Y": "Y\nН",
    "KC_U": "U\nГ",
    "KC_I": "I\nШ (Щ)",
    "KC_O": "O\nЗ",
    "KC_P": "P\nХ",
    "KC_LBRACKET": ",\n;",
    "KC_RBRACKET": ".\n",
    "KC_BSLASH": "/ | (\\ ¦)",

    "KC_A": "A\nФ",
    "KC_S": "S\nЫ",
    "KC_D": "D\nВ",
    "KC_F": "F\nА",
    "KC_G": "G\nП",
    "KC_H": "H\nР",
    "KC_J": "J\nО",
    "KC_K": "K\nЛ",
    "KC_L": "L\nД",
    "KC_SCOLON": "≈ ~\nЖ",
    "KC_QUOTE": "",

    "KC_NONUS_BSLASH": "NO_OP",
    "KC_Z": "Z\nЯ",
    "KC_X": "X\nЧ",
    "KC_C": "C\nС",
    "KC_V": "V\nМ",
    "KC_B": "B\nИ",
    "KC_N": "N\nТ",
    "KC_M": "M\nЬ (Ъ)",
    "KC_COMMA": "&\nБ",
    "KC_DOT": "[ {\nЮ",
    "KC_SLASH": "] }\nЭ"
}

universal_braindefender_standard = {
    
    "KC_GRAVE": "' \"\n(` •)",
    "KC_1": '! 1',
    "KC_2": '@ 2',
    "KC_3": "# 3",
    "KC_4": "$ 4",
    "KC_5": "% 5",
    "KC_6": "^ 6",
    "KC_7": "? 7",
    "KC_8": "* 8",
    "KC_9": "( 9",
    "KC_0": ") 0",
    "KC_MINUS": "- _\n–",
    "KC_EQUAL": "= +\n≠ ±",

    "KC_Q": "Q\nЙ",
    "KC_W": "W\nЦ",
    "KC_E": "E\nУ",
    "KC_R": "R\nК",
    "KC_T": "T\nЕ (Ë)",
    "KC_Y": "Y\nН",
    "KC_U": "U\nГ",
    "KC_I": "I\nШ",
    "KC_O": "O\nЩ",
    "KC_P": "P\nЗ",
    "KC_LBRACKET": "[ {\nХ",
    "KC_RBRACKET": "] }\nБ",
    "KC_BSLASH": "/ | (\\ ¦)",

    "KC_A": "A\nФ",
    "KC_S": "S\nЫ",
    "KC_D": "D\nВ",
    "KC_F": "F\nА",
    "KC_G": "G\nП",
    "KC_H": "H\nР",
    "KC_J": "J\nО",
    "KC_K": "K\nЛ",
    "KC_L": "L\nД",
    "KC_SCOLON": "=>\nЖ",
    "KC_QUOTE": "~ ≈\nЭ",

    "KC_NONUS_BSLASH": "NO_OP",
    "KC_Z": "Z\nЯ",
    "KC_X": "X\nЧ",
    "KC_C": "C\nС",
    "KC_V": "V\nМ",
    "KC_B": "B\nИ",
    "KC_N": "N\nТ",
    "KC_M": "M\nЬ (Ъ)",
    "KC_COMMA": ", ;",
    "KC_DOT": ". :",
    "KC_SLASH": "&\nЮ"
}
