# coding: utf-8

keymap = {
    "KC_GRAVE": ";\n°  ~",
    "KC_1": "+\n1  ^",
    "KC_2": "ľ\n4  ˘",
    "KC_3": "š\n3  °",
    "KC_4": "č\n4  ˛",
    "KC_5": "ť\n5  `",
    "KC_6": "ž\n6  ˙",
    "KC_7": "ý\n7  ˝",
    "KC_8": "á\n8  ¨",
    "KC_9": "í\n9  ¸",
    "KC_0": "é\n0",
    "KC_Q": "Q\n  \\",
    "KC_W": "W\n  |",
    "KC_E": "E\n  €",
    "KC_P": "P\n  '",
    "KC_MINUS": "=\n%",
    "KC_EQUAL": "´\nˇ",
    "KC_LBRACKET": "ú\n/  ÷",
    "KC_RBRACKET": "ä\n(  ×",
    "KC_BSLASH": "ň\n)",
    "KC_SCOLON": "ô\n\"",
    "KC_QUOTE": "§\n!",
    "KC_NONUS_BSLASH": "&\n*  <",
    "KC_Z": "Z\n  >",
    "KC_X": "X\n  #",
    "KC_V": "V\n  @",
    "KC_B": "B\n  {",
    "KC_N": "N\n  }",
    "KC_COMMA": ",\n?",
    "KC_DOT": ".\n:",
    "KC_SLASH": "-\n_",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)"
}