# coding: utf-8

keymap = {
    "KC_GRAVE": ";\n°  ~",
    "KC_1": "1\n+  ^",
    "KC_2": "2\nľ  ˘",
    "KC_3": "3\nš  °",
    "KC_4": "4\nč  ˛",
    "KC_5": "5\nť  `",
    "KC_6": "6\nž  ˙",
    "KC_7": "7\ný  ˝",
    "KC_8": "8\ná  ¨",
    "KC_9": "9\ní  ¸",
    "KC_0": "0\né",
    #alt gr overrides only
    "KC_Q": "Q\n  \\",
    "KC_W": "W\n  |",
    "KC_E": "E\n  €",
    "KC_P": "P\n  '",
    "KC_Z": "Z\n  >",
    "KC_X": "X\n  #",
    "KC_V": "V\n  @",
    "KC_B": "B\n  {",
    "KC_N": "N\n  }",
    #back to normal overrides
    "KC_MINUS":         "%\n=",
    "KC_EQUAL":         "ˇ\n´",
    "KC_LBRACKET":      "/\nú  ÷",
    "KC_RBRACKET":      "(\nä  ×",
    "KC_BSLASH":        ")\nň",
    "KC_SCOLON":        "\"\nô",
    "KC_QUOTE":         "!\n§",
    "KC_NONUS_BSLASH":  "*\n&  <",
    "KC_COMMA":         "?\n,",
    "KC_DOT":           ":\n.",
    "KC_SLASH":         "_\n-",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)",
    "KC_TILDE":  "°\n~",
    "KC_EXCLAIM":  "1\n^",
    "KC_AT":    "2\n˘",
    "KC_HASH":  "3\n°",
    "KC_DOLLAR":   "4\n˛",
    "KC_PERCENT":  "5\n`",
    "KC_CIRCUMFLEX":  "6\n˙",
    "KC_AMPERSAND":  "7\n˝",
    "KC_ASTERISK":  "8\n¨",
    "KC_LEFT_PAREN":  "9\n¸",
    "KC_RIGHT_PAREN":  "0",
    "KC_UNDERSCORE":  "=\n%",
    "KC_PLUS":  "´\nˇ",
    "KC_LEFT_CURLY_BRACE": "/\n÷",
    "KC_RIGHT_CURLY_BRACE": "(\n×",
    "KC_LEFT_ANGLE_BRACKET": "?",
    "KC_RIGHT_ANGLE_BRACKET": ":",
    "KC_COLON": "\"",
    "KC_QUESTION": "_",
    "KC_DOUBLE_QUOTE": '!'
}