# coding: utf-8

keymap = {
    "KC_GRAVE": ";\n°  ~",
    "KC_1": "1\n+  ^",
    "KC_2": "2\nľ  ˘",
    "KC_3": "3\nš  °",
    "KC_4": "4\nč  ˛",
    "KC_5": "5\nť  `",
    "KC_6": "6\nž  ˙",
    "KC_7": "7\ný  ˝",
    "KC_8": "8\ná  ¨",
    "KC_9": "9\ní  ¸",
    "KC_0": "0\né",
    "KC_Q": "Q\n  \\",
    "KC_W": "W\n  |",
    "KC_E": "E\n  €",
    "KC_P": "P\n  '",
    "KC_MINUS": "%\n=",
    "KC_EQUAL": "ˇ\n´",
    "KC_LBRACKET": "/\nú  ÷",
    "KC_RBRACKET": "(\nä  ×",
    "KC_BSLASH": ")\nň",
    "KC_SCOLON": "\"\nô",
    "KC_QUOTE": "!\n§",
    "KC_NONUS_BSLASH": "*\n&  <",
    "KC_Z": "Z\n  >",
    "KC_X": "X\n  #",
    "KC_V": "V\n  @",
    "KC_B": "B\n  {",
    "KC_N": "N\n  }",
    "KC_COMMA": "?\n,",
    "KC_DOT": ":\n.",
    "KC_SLASH": "_\n-",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)",
    "KC_TILD":  "°\n~",
    "KC_EXLM":  "1\n^",
    "KC_AT":    "2\n˘",
    "KC_HASH":  "3\n°",
    "KC_DLR":   "4\n˛",
    "KC_PERC":  "5\n`",
    "KC_CIRC":  "6\n˙",
    "KC_AMPR":  "7\n˝",
    "KC_ASTR":  "8\n¨",
    "KC_LPRN":  "9\n¸",
    "KC_RPRN":  "0",
    "KC_UNDS":  "=\n%",
    "KC_PLUS":  "´\nˇ",
    "KC_LCBR": "/\n÷",
    "KC_RCBR": "(\n×",
    "KC_LT": "?",
    "KC_GT": ":",
    "KC_COLN": "\"",
    "KC_QUES": "_",
    "KC_DQUO": '!'
}