# coding: utf-8

keymap = {
    "KC_GRAVE": "°\n| \\",
    "KC_1": "!\n1 |",
    "KC_2": "\"\n2 @",
    "KC_3": "·\n3 #",
    "KC_4": "$\n4 ~",
    "KC_5": "%\n5 €",
    "KC_6": "&\n6 ¬",
    "KC_7": "/\n7",
    "KC_8": "(\n8",
    "KC_9": ")\n9",
    "KC_0": "=\n0",
    "KC_E": "E\n     €",
    "KC_MINUS": "?\n'",
    "KC_EQUAL": "¡\n¿",
    "KC_LBRACKET": "^\n` [",
    "KC_RBRACKET": "*\n+ ]",
    "KC_SCOLON": "Ñ",
    "KC_QUOTE": "¨\n´ {",
    "KC_BSLASH": "Ç\n     }",
    "KC_NONUS_HASH": "Ç\n     }",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_COMMA": ";\n,",
    "KC_DOT": ".\n:",
    "KC_SLASH": "_\n-"
}

keymap_dvorak = {
    "KC_GRAVE": "°\n| \\",
    "KC_1": "!\n1 |",
    "KC_2": "\"\n2 @",
    "KC_3": "·\n3 #",
    "KC_4": "$\n4 ~",
    "KC_5": "%\n5 €",
    "KC_6": "&\n6 ¬",
    "KC_7": "/\n7",
    "KC_8": "(\n8",
    "KC_9": ")\n9",
    "KC_0": "=\n0",
    "KC_MINUS": "?\n'",
    "KC_EQUAL": "¡\n¿",
    "KC_Q": ":\n.",
    "KC_W": ";\n,",
    "KC_E": "Ñ",
    "KC_R": "P",
    "KC_T": "Y",
    "KC_Y": "F",
    "KC_U": "G",
    "KC_I": "C",
    "KC_O": "H",
    "KC_P": "L",
    "KC_LBRACKET": "^\n` [",
    "KC_RBRACKET": "*\n+ ]",
    "KC_S": "O",
    "KC_D": "E\n     €",
    "KC_F": "U",
    "KC_G": "I",
    "KC_H": "D",
    "KC_J": "R",
    "KC_K": "T",
    "KC_L": "N",
    "KC_SCOLON": "S",
    "KC_QUOTE": "¨\n´ {",
    "KC_BSLASH": "Ç\n     }",
    "KC_NONUS_HASH": "Ç\n     }",
    "KC_NONUS_BSLASH": ">\n<",
    "KC_Z": "_\n-",
    "KC_X": "Q",
    "KC_C": "J",
    "KC_V": "K",
    "KC_B": "X",
    "KC_N": "B",
    "KC_COMMA": "W",
    "KC_DOT": "V",
    "KC_SLASH": "Z",
}