# coding: utf-8

keymap = {
    "KC_GRAVE": "°\n§",
    "KC_1": ' +\n1   ¦',
    "KC_2": '"\n2   @',
    "KC_3": "*\n3   #",
    "KC_4": "ç\n4   °",
    "KC_5": "%\n5   §",
    "KC_6": "&\n6   ¬",
    "KC_7": "/\n7   |",
    "KC_8": "(\n8   ¢",
    "KC_9": ")\n9",
    "KC_0": "=\n0",
    "KC_MINUS": "?\n'   ´",
    "KC_EQUAL": "`\n^   ~",
    "KC_LBRACKET": "è  ü \nü  è  [",
    "KC_RBRACKET": '!\n"    ]',
    "KC_SCOLON": "é  ö\nö  é",
    "KC_QUOTE": "à  ä\nä  à  {",
    "KC_NONUS_HASH": "£\n$   }",
    "KC_NONUS_BSLASH": ">\n<   \\",
    "KC_COMMA": ";\n,",
    "KC_DOT": ":\n.",
    "KC_SLASH": "_\n-",
    "KC_BSLASH": "£\n$   }",
    "KC_TILD": "°",
    "KC_AT": "\"",
    "KC_DLR": "ç",
    "KC_CIRC": "&",
    "KC_AMPR": "/",
    "KC_ASTR": "(",
    "KC_LPRN": ")",
    "KC_RPRN": "=",
    "KC_UNDS": "?",
    "KC_PLUS": "`",
    "KC_LCBR": "ü",
    "KC_RCBR": "!",
    "KC_LT": ";",
    "KC_GT": ":",
    "KC_COLN": "ö",
    "KC_PIPE": "£",
    "KC_QUES": "_",
    "KC_DQUO": "ä",
    "KC_RALT": "AltGr",
    "RALT(kc)": "AltGr\n(kc)",
    "RALT_T(kc)": "AltGr_T\n(kc)"
}
