# coding: utf-8

keymap = {
    "KC_GRAVE": "é\n\"",
    "KC_1": "!\n1",
    "KC_2": "'\n2    £",
    "KC_3": "^\n3    #",
    "KC_4": "+\n4    $",
    "KC_5": "%\n5",
    "KC_6": "&\n6",
    "KC_7": "/\n7    {",
    "KC_8": "(\n8    [",
    "KC_9": ")\n9    ]",
    "KC_0": "=\n0    }",
    "KC_MINUS": "?\n*    \\",
    "KC_EQUAL": "_\n-    ",
    "KC_Q": "Q\n    @",
    "KC_E": "E\n    €",
    "KC_T": "T\n    ₺",
    "KC_A": "A\n    æ",
    "KC_S": "S\n    ß",
    "KC_LBRACKET": "Ğ\n    ¨",
    "KC_RBRACKET": "Ü\n    ~",
    "KC_SCOLON": "Ş\n    ´",
    "KC_QUOTE": "İ",
    "KC_COMMA": "Ö",
    "KC_DOT": "Ç",
    "KC_NONUS_HASH": ";\n,    `",
    "KC_NONUS_BSLASH": ">\n<    |",
    "KC_SLASH": ":\n."
}