# SPDX-License-Identifier: GPL-2.0-or-later

ansi_100 = r"""
[["KC_ESCAPE",{"x":1},"KC_F1","KC_F2","KC_F3","KC_F4",{"x":0.5},"KC_F5","KC_F6","KC_F7","KC_F8",{"x":0.5},"KC_F9","KC_F10","KC_F11","KC_F12",{"x":0.25},"KC_PSCREEN","KC_SCROLLLOCK","KC_PAUSE"],[{"y":0.25},"KC_GRAVE","KC_1","KC_2","KC_3","KC_4","KC_5","KC_6","KC_7","KC_8","KC_9","KC_0","KC_MINUS","KC_EQUAL",{"w":2},"KC_BSPACE",{"x":0.25},"KC_INSERT","KC_HOME","KC_PGUP",{"x":0.25},"KC_NUMLOCK","KC_KP_SLASH","KC_KP_ASTERISK","KC_KP_MINUS"],[{"w":1.5},"KC_TAB","KC_Q","KC_W","KC_E","KC_R","KC_T","KC_Y","KC_U","KC_I","KC_O","KC_P","KC_LBRACKET","KC_RBRACKET",{"w":1.5},"KC_BSLASH",{"x":0.25},"KC_DELETE","KC_END","KC_PGDOWN",{"x":0.25},"KC_KP_7","KC_KP_8","KC_KP_9","KC_KP_PLUS"],[{"w":1.75},"KC_CAPSLOCK","KC_A","KC_S","KC_D","KC_F","KC_G","KC_H","KC_J","KC_K","KC_L","KC_SCOLON","KC_QUOTE",{"w":2.25},"KC_ENTER",{"x":3.5},"KC_KP_4","KC_KP_5","KC_KP_6","KC_KP_COMMA"],[{"w":2.25},"KC_LSHIFT","KC_Z","KC_X","KC_C","KC_V","KC_B","KC_N","KC_M","KC_COMMA","KC_DOT","KC_SLASH",{"w":2.75},"KC_RSHIFT",{"x":1.25},"KC_UP",{"x":1.25},"KC_KP_1","KC_KP_2","KC_KP_3","KC_KP_EQUAL"],[{"w":1.25},"KC_LCTRL",{"w":1.25},"KC_LGUI",{"w":1.25},"KC_LALT",{"w":6.25},"KC_SPACE",{"w":1.25},"KC_RALT",{"w":1.25},"KC_RGUI",{"w":1.25},"KC_APPLICATION",{"w":1.25},"KC_RCTRL",{"x":0.25},"KC_LEFT","KC_DOWN","KC_RIGHT",{"x":0.25,"w":2},"KC_KP_0","KC_KP_DOT","KC_KP_ENTER"]]
"""

ansi_80 = r"""
[["KC_ESCAPE",{"x":1},"KC_F1","KC_F2","KC_F3","KC_F4",{"x":0.5},"KC_F5","KC_F6","KC_F7","KC_F8",{"x":0.5},"KC_F9","KC_F10","KC_F11","KC_F12",{"x":0.25},"KC_PSCREEN","KC_SCROLLLOCK","KC_PAUSE"],[{"y":0.25},"KC_GRAVE","KC_1","KC_2","KC_3","KC_4","KC_5","KC_6","KC_7","KC_8","KC_9","KC_0","KC_MINUS","KC_EQUAL",{"w":2},"KC_BSPACE",{"x":0.25},"KC_INSERT","KC_HOME","KC_PGUP"],[{"w":1.5},"KC_TAB","KC_Q","KC_W","KC_E","KC_R","KC_T","KC_Y","KC_U","KC_I","KC_O","KC_P","KC_LBRACKET","KC_RBRACKET",{"w":1.5},"KC_BSLASH",{"x":0.25},"KC_DELETE","KC_END","KC_PGDOWN"],[{"w":1.75},"KC_CAPSLOCK","KC_A","KC_S","KC_D","KC_F","KC_G","KC_H","KC_J","KC_K","KC_L","KC_SCOLON","KC_QUOTE",{"w":2.25},"KC_ENTER"],[{"w":2.25},"KC_LSHIFT","KC_Z","KC_X","KC_C","KC_V","KC_B","KC_N","KC_M","KC_COMMA","KC_DOT","KC_SLASH",{"w":2.75},"KC_RSHIFT",{"x":1.25},"KC_UP"],[{"w":1.25},"KC_LCTRL",{"w":1.25},"KC_LGUI",{"w":1.25},"KC_LALT",{"w":6.25},"KC_SPACE",{"w":1.25},"KC_RALT",{"w":1.25},"KC_RGUI",{"w":1.25},"KC_APPLICATION",{"w":1.25},"KC_RCTRL",{"x":0.25},"KC_LEFT","KC_DOWN","KC_RIGHT"]]
"""

ansi_70 = r"""
[["KC_ESCAPE",{"x":1},"KC_F1","KC_F2","KC_F3","KC_F4",{"x":0.5},"KC_F5","KC_F6","KC_F7","KC_F8",{"x":0.5},"KC_F9","KC_F10","KC_F11","KC_F12"],[{"y":0.25},"KC_GRAVE","KC_1","KC_2","KC_3","KC_4","KC_5","KC_6","KC_7","KC_8","KC_9","KC_0","KC_MINUS","KC_EQUAL",{"w":2},"KC_BSPACE"],[{"w":1.5},"KC_TAB","KC_Q","KC_W","KC_E","KC_R","KC_T","KC_Y","KC_U","KC_I","KC_O","KC_P","KC_LBRACKET","KC_RBRACKET",{"w":1.5},"KC_BSLASH"],[{"w":1.75},"KC_CAPSLOCK","KC_A","KC_S","KC_D","KC_F","KC_G","KC_H","KC_J","KC_K","KC_L","KC_SCOLON","KC_QUOTE",{"w":2.25},"KC_ENTER"],[{"w":2.25},"KC_LSHIFT","KC_Z","KC_X","KC_C","KC_V","KC_B","KC_N","KC_M","KC_COMMA","KC_DOT","KC_SLASH",{"w":2.75},"KC_RSHIFT"],[{"w":1.25},"KC_LCTRL",{"w":1.25},"KC_LGUI",{"w":1.25},"KC_LALT",{"w":6.25},"KC_SPACE",{"w":1.25},"KC_RALT",{"w":1.25},"KC_RGUI",{"w":1.25},"KC_APPLICATION",{"w":1.25},"KC_RCTRL"]]
"""

iso_100 = r"""
[["KC_ESCAPE",{"x":1},"KC_F1","KC_F2","KC_F3","KC_F4",{"x":0.5},"KC_F5","KC_F6","KC_F7","KC_F8",{"x":0.5},"KC_F9","KC_F10","KC_F11","KC_F12",{"x":0.25},"KC_PSCREEN","KC_SCROLLLOCK","KC_PAUSE"],[{"y":0.25},"KC_GRAVE","KC_1","KC_2","KC_3","KC_4","KC_5","KC_6","KC_7","KC_8","KC_9","KC_0","KC_MINUS","KC_EQUAL","KC_JYEN","KC_BSPACE",{"x":0.25},"KC_INSERT","KC_HOME","KC_PGUP",{"x":0.25},"KC_NUMLOCK","KC_KP_SLASH","KC_KP_ASTERISK","KC_KP_MINUS"],[{"w":1.5},"KC_TAB","KC_Q","KC_W","KC_E","KC_R","KC_T","KC_Y","KC_U","KC_I","KC_O","KC_P","KC_LBRACKET","KC_RBRACKET",{"x":0.25,"w":1.25,"h":2},"KC_ENTER",{"x":0.25},"KC_DELETE","KC_END","KC_PGDOWN",{"x":0.25},"KC_KP_7","KC_KP_8","KC_KP_9","KC_KP_PLUS"],[{"w":1.75},"KC_CAPSLOCK","KC_A","KC_S","KC_D","KC_F","KC_G","KC_H","KC_J","KC_K","KC_L","KC_SCOLON","KC_QUOTE","KC_NONUS_HASH",{"x":4.75},"KC_KP_4","KC_KP_5","KC_KP_6","KC_KP_COMMA"],[{"w":1.25},"KC_LSHIFT","KC_NONUS_BSLASH","KC_Z","KC_X","KC_C","KC_V","KC_B","KC_N","KC_M","KC_COMMA","KC_DOT","KC_SLASH","KC_RO",{"w":1.75},"KC_RSHIFT",{"x":1.25},"KC_UP",{"x":1.25},"KC_KP_1","KC_KP_2","KC_KP_3","KC_KP_EQUAL"],[{"w":1.25},"KC_LCTRL",{"w":1.25},"KC_LGUI",{"w":1.25},"KC_LALT",{"w":1.25},"KC_MHEN",{"w":2.5},"KC_SPACE",{"w":1.25},"KC_HENK",{"w":1.25},"KC_KANA",{"w":1.25},"KC_RALT",{"w":1.25},"KC_RGUI",{"w":1.25},"KC_APPLICATION",{"w":1.25},"KC_RCTRL",{"x":0.25},"KC_LEFT","KC_DOWN","KC_RIGHT",{"x":0.25,"w":2},"KC_KP_0","KC_KP_DOT","KC_KP_ENTER"]]
"""

iso_80 = r"""
[["KC_ESCAPE",{"x":1},"KC_F1","KC_F2","KC_F3","KC_F4",{"x":0.5},"KC_F5","KC_F6","KC_F7","KC_F8",{"x":0.5},"KC_F9","KC_F10","KC_F11","KC_F12",{"x":0.25},"KC_PSCREEN","KC_SCROLLLOCK","KC_PAUSE"],[{"y":0.25},"KC_GRAVE","KC_1","KC_2","KC_3","KC_4","KC_5","KC_6","KC_7","KC_8","KC_9","KC_0","KC_MINUS","KC_EQUAL","KC_JYEN","KC_BSPACE",{"x":0.25},"KC_INSERT","KC_HOME","KC_PGUP"],[{"w":1.5},"KC_TAB","KC_Q","KC_W","KC_E","KC_R","KC_T","KC_Y","KC_U","KC_I","KC_O","KC_P","KC_LBRACKET","KC_RBRACKET",{"x":0.25,"w":1.25,"h":2},"KC_ENTER",{"x":0.25},"KC_DELETE","KC_END","KC_PGDOWN"],[{"w":1.75},"KC_CAPSLOCK","KC_A","KC_S","KC_D","KC_F","KC_G","KC_H","KC_J","KC_K","KC_L","KC_SCOLON","KC_QUOTE","KC_NONUS_HASH"],[{"w":1.25},"KC_LSHIFT","KC_NONUS_BSLASH","KC_Z","KC_X","KC_C","KC_V","KC_B","KC_N","KC_M","KC_COMMA","KC_DOT","KC_SLASH","KC_RO",{"w":1.75},"KC_RSHIFT",{"x":1.25},"KC_UP"],[{"w":1.25},"KC_LCTRL",{"w":1.25},"KC_LGUI",{"w":1.25},"KC_LALT",{"w":1.25},"KC_MHEN",{"w":2.5},"KC_SPACE",{"w":1.25},"KC_HENK",{"w":1.25},"KC_KANA",{"w":1.25},"KC_RALT",{"w":1.25},"KC_RGUI",{"w":1.25},"KC_APPLICATION",{"w":1.25},"KC_RCTRL",{"x":0.25},"KC_LEFT","KC_DOWN","KC_RIGHT"]]
"""

iso_70 = r"""
[["KC_ESCAPE",{"x":1},"KC_F1","KC_F2","KC_F3","KC_F4",{"x":0.5},"KC_F5","KC_F6","KC_F7","KC_F8",{"x":0.5},"KC_F9","KC_F10","KC_F11","KC_F12"],[{"y":0.25},"KC_GRAVE","KC_1","KC_2","KC_3","KC_4","KC_5","KC_6","KC_7","KC_8","KC_9","KC_0","KC_MINUS","KC_EQUAL","KC_JYEN","KC_BSPACE"],[{"w":1.5},"KC_TAB","KC_Q","KC_W","KC_E","KC_R","KC_T","KC_Y","KC_U","KC_I","KC_O","KC_P","KC_LBRACKET","KC_RBRACKET",{"x":0.25,"w":1.25,"h":2},"KC_ENTER"],[{"w":1.75},"KC_CAPSLOCK","KC_A","KC_S","KC_D","KC_F","KC_G","KC_H","KC_J","KC_K","KC_L","KC_SCOLON","KC_QUOTE","KC_NONUS_HASH"],[{"w":1.25},"KC_LSHIFT","KC_NONUS_BSLASH","KC_Z","KC_X","KC_C","KC_V","KC_B","KC_N","KC_M","KC_COMMA","KC_DOT","KC_SLASH","KC_RO",{"w":1.75},"KC_RSHIFT"],[{"w":1.25},"KC_LCTRL",{"w":1.25},"KC_LGUI",{"w":1.25},"KC_LALT",{"w":1.25},"KC_MHEN",{"w":2.5},"KC_SPACE",{"w":1.25},"KC_HENK",{"w":1.25},"KC_KANA",{"w":1.25},"KC_RALT",{"w":1.25},"KC_RGUI",{"w":1.25},"KC_APPLICATION",{"w":1.25},"KC_RCTRL"]]
"""

mods = r"""
[["RESET",{"x":1},"KC_GESC","KC_LSPO","KC_RSPC","KC_LCPO","KC_RCPC","KC_LAPO","KC_RAPC","KC_SFTENT"],
[{"y":0.25},"OSM(MOD_LSFT)","OSM(MOD_LCTL)","OSM(MOD_LALT)","OSM(MOD_LGUI)",{"x":0.25},"OSM(MOD_RSFT)","OSM(MOD_RCTL)","OSM(MOD_RALT)","OSM(MOD_RGUI)",{"x":0.25},"OSM(MOD_LCTL|MOD_LSFT)","OSM(MOD_LCTL|MOD_LALT)","OSM(MOD_LCTL|MOD_LGUI)","OSM(MOD_LSFT|MOD_LALT)","OSM(MOD_LSFT|MOD_LGUI)","OSM(MOD_LALT|MOD_LGUI)","OSM(MOD_LCTL|MOD_LSFT|MOD_LGUI)","OSM(MOD_LCTL|MOD_LALT|MOD_LGUI)","OSM(MOD_LSFT|MOD_LALT|MOD_LGUI)","OSM(MOD_MEH)","OSM(MOD_HYPR)"],
[{"y":0.25},"LSFT(kc)","LCTL(kc)","LALT(kc)","LGUI(kc)",{"x":0.25},"RSFT(kc)","RCTL(kc)","RALT(kc)","RGUI(kc)",{"x":0.25},"C_S(kc)","LCA(kc)","LCG(kc)","LSA(kc)","SGUI(kc)","RCG(kc)",{"x":1},"LCAG(kc)",{"x":1},"MEH(kc)","HYPR(kc)"],
["LSFT_T(kc)","LCTL_T(kc)","LALT_T(kc)","LGUI_T(kc)",{"x":0.25},"RSFT_T(kc)","RCTL_T(kc)","RALT_T(kc)","RGUI_T(kc)",{"x":0.25},"C_S_T(kc)","LCA_T(kc)","LCG_T(kc)","LSA_T(kc)","SGUI_T(kc)","RCG_T(kc)","RCAG_T(kc)","LCAG_T(kc)",{"x":1},"MEH_T(kc)","ALL_T(kc)"],
[{"y":0.5},"MAGIC_SWAP_CONTROL_CAPSLOCK","MAGIC_CAPSLOCK_TO_CONTROL",{"x":0.25},"MAGIC_SWAP_LCTL_LGUI","MAGIC_SWAP_RCTL_RGUI","MAGIC_SWAP_CTL_GUI",{"x":1.25},"MAGIC_SWAP_LALT_LGUI","MAGIC_SWAP_RALT_RGUI","MAGIC_SWAP_ALT_GUI",{"x":1.25},"MAGIC_UNNO_GUI",{"x":0.25},"MAGIC_SWAP_GRAVE_ESC",{"x":0.25},"MAGIC_SWAP_BACKSLASH_BACKSPACE"],
[{"y":-0.5,"x":5.25},"MAGIC_TOGGLE_CTL_GUI",{"x":3.25},"MAGIC_TOGGLE_ALT_GUI"],
[{"y":-0.5},"MAGIC_UNSWAP_CONTROL_CAPSLOCK","MAGIC_UNCAPSLOCK_TO_CONTROL",{"x":0.25},"MAGIC_UNSWAP_LCTL_LGUI","MAGIC_UNSWAP_RCTL_RGUI","MAGIC_UNSWAP_CTL_GUI",{"x":1.25},"MAGIC_UNSWAP_LALT_LGUI","MAGIC_UNSWAP_RALT_RGUI","MAGIC_UNSWAP_ALT_GUI",{"x":1.25},"MAGIC_NO_GUI",{"x":0.25},"MAGIC_UNSWAP_GRAVE_ESC",{"x":0.25},"MAGIC_UNSWAP_BACKSLASH_BACKSPACE"],
[{"y":0.5},"MAGIC_HOST_NKRO","MAGIC_UNHOST_NKRO","MAGIC_TOGGLE_NKRO",{"x":1},"MAGIC_EE_HANDS_LEFT","MAGIC_EE_HANDS_RIGHT"],
["AU_ON","AU_OFF","AU_TOG",{"x":1},"CLICKY_TOGGLE","CLICKY_UP","CLICKY_DOWN","CLICKY_RESET",{"x":1},"MU_ON","MU_OFF","MU_TOG","MU_MOD"],
["HPT_ON","HPT_OFF","HPT_TOG","HPT_RST","HPT_FBK","HPT_BUZ","HPT_MODI","HPT_MODD","HPT_CONT","HPT_CONI","HPT_COND","HPT_DWLI","HPT_DWLD"],
["KC_ASDN","KC_ASUP","KC_ASRP","KC_ASON","KC_ASOFF","KC_ASTG",{"x":1},"CMB_ON","CMB_OFF","CMB_TOG"]]
"""
