name: Test

on: [push, pull_request]

jobs:
  test-linux:
    runs-on: ubuntu-22.04

    steps:
    - uses: actions/checkout@v4

    - name: Install dependencies
      run: |
        sudo apt-get update
        sudo apt-get install -y libusb-1.0-0-dev libudev-dev ruby ruby-dev rubygems build-essential desktop-file-utils wget unzip zlib1g-dev liblzma-dev libssl-dev git imagemagick file libfuse2 clang
        sudo gem install --no-document fpm

    - name: Set up Python 3.6
      run: CC=clang ./util/setup_python36.sh

    - name: Setup venv
      run: |
        export LD_LIBRARY_PATH=$(pwd)/util/python36/prefix/lib/
        ./util/python36/prefix/bin/python3 -m venv venv
        . venv/bin/activate
        pip install -r test-requirements.txt

    - name: Run tests
      run: |
        export LD_LIBRARY_PATH=$(pwd)/util/python36/prefix/lib/
        source venv/bin/activate
        pytest -v src/main/python/test
